spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
      
# ===========================================
# Application Specific Properties
# ===========================================      

app:
  security: 
    authentication: 
      jwt: 
        secret: my-secret-token-to-change-in-production
        tokenValidityInSeconds: 86400